config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'events#index'
  resources :events
  resources :users, only: :show
  resources :attended_events, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User'

    has_many :attended_events, dependent: :destroy
    has_many :attendees, through: :attended_events, source: :user

    scope :past_events, -> { where('date < ?', Time.now) }
    scope :future_events, -> { where('date >= ?', Time.now) }
    scope :not_private, -> { where('private == 0') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, class_name: 'Event', foreign_key: :creator_id, dependent: :destroy

  has_many :attended_events
  has_many :attending_events, through: :attended_events, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attended_events_controller.rb
class AttendedEventsController < ApplicationController
    def new
        @attended_event = AttendedEvent.new
        @event_id = params[:event]
    end
    
    def create
        @user = User.find(params[:attended_event][:user_id])
        @event = Event.find(params[:attended_event][:event_id])

        begin
            @event.attendees << @user
        rescue 
            flash[:alert] = 'Unable to save event'
        end
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @user = User.find(current_user.id)
        @event = Event.find(params[:id])

        @event.attendees.delete(@user)
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    
    def index
        @events = Event.all
    end

    def show
       @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @user = User.find(current_user.id)
        @event = Event.new(event_params)
        @event.creator = @user

        if @event.save
            redirect_to user_path(@user)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @user = User.find(current_user.id)
        @event = Event.find(params[:id])

        if @event.update(event_params)
            redirect_to user_path(@user)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(current_user.id)
        @event = Event.find(params[:id])

        @event.destroy
        
        redirect_to user_path(@user)
    end

    private

    def event_params
        params.require(:event).permit(:title, :body, :date, :private)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attended_events_helper.rb
module AttendedEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attended_events/_header.html.erb
<div class='header'>
    <div class='link-container'>
        <%= link_to 'All Events', root_path, class: 'link' %>
        <%= link_to 'Create Event', new_event_path, class: 'link' %>
        <% if user_signed_in? %>
            <%= link_to 'My Events', user_path(current_user), class: 'link' %>
            <%= link_to 'Sign Out', destroy_user_session_path, data: { 'turbo_method': :delete } %>
        <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'link' %>
        <% end %>
    </div>
</div>

app/views/attended_events/new.html.erb
<%= render "header" %>

<%= form_with model: @attended_event do |form| %>
    <div>
        <%= form.label :user_id, "Invite User" %>
        <%= form.text_field :user_id, placeholder: "Enter user ID" %>
        <%= form.hidden_field :event_id, value: @event_id %>
    </div>
    <%= form.submit "Invite User" %>
<% end %>
    

app/views/events/_event_form.html.erb
<%= form_with model: event do |form| %>
    <div>
        <%= form.label :title, "Event Name" %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body, "Event Details" %>
        <%= form.text_area :body %>
    </div>
    <div>
        <%= form.label :date, "Event Date" %>
        <%= form.date_select :date %>
    </div>
    <div>
        <%= form.label :private, "Private Event?" %>
        <%= form.check_box :private %>
    </div>
    <%= form.submit "Submit" %>
<% end %>

app/views/events/_list_events.html.erb
<div class='list-events'>
        <div><%= link_to event.title, event_path(event) %></div>
        <div><%= event.date %></div>
        <div><%= event.body %></div>
        <% if user_signed_in? %>
                <%= link_to 'Attend Event',  attended_events_path(attended_event: { user_id: current_user.id, event_id: event }), data: { turbo_method: :post } %>
        <% end %>
</div>

app/views/events/edit.html.erb
<%= render "header" %>

<h1>Edit Your Event:</h1>
<%= render "event_form", event: @event %>

app/views/events/index.html.erb
<% if flash.any? %>
    <div class='flash'>
        <%= flash[:alert] %>
    </div>
<% end %>

<%= render "header" %>

<h1>Upcoming Events:</h1>
<% @events.not_private.future_events.each do |event| %>
    <%= render "list_events", event: event %>
<% end %>

<h1>Past Events:</h1>
<% @events.not_private.past_events.each do |event| %>
    <%= render "list_events", event: event %>
<% end %>

app/views/events/new.html.erb
<%= render "header" %>

<h1>Create Your Event!</h1>
<%= render "event_form", event: @event %>

app/views/events/show.html.erb
<%= render "header" %>

<div style="display: flex; flex-direction: column; margin: 10px;">
    <div><%= @event.title %></div>
    <div><%= @event.date %></div>
    <div><%= @event.body %></div>
</div>

<h2>Attendee List:</h2>
<ul>
    <% @event.attendees.each do |attendee| %>
        <li><%= attendee.email %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "private_events" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= render "header" %>

<h1>Created Events:</h1>
<div style="margin: 10px;">
    <% @user.created_events.each do |event| %>
        <div style="display: flex; flex-direction: column; margin: 10px;">
            <div><%= link_to event.title, event_path(event) %></div>
            <div><%= event.date %></div>
            <div><%= event.body %></div>
            <div>
                <%= link_to "Invite", new_attended_event_path(event: event) %>
                <%= link_to "Edit", edit_event_path(event) %>
                <%= link_to "Delete", event_path(event), data: { 'turbo_method': :delete, 'turbo_confirm': 'Are you sure?' } %>
            </div>
        </div>
    <% end %>
</div>

<h1>Upcoming Events:</h1>
<ul style='margin: 10px;'>
    <% @user.attending_events.future_events.each do |event| %>
        <li style='margin: 10px;'><%= link_to event.title, event_path(event) %></li>
        <%= link_to 'Unattend Event', attended_event_path(event), data: { 'turbo_method': :delete } %>
    <% end %>
</ul>

<h1>Past Events:</h1>
<ul style='margin: 10px;'>
    <% @user.attending_events.past_events.each do |event| %>
        <li style='margin: 10px;'><%= link_to event.title, event_path(event) %></li>
        <%= link_to 'Unattend Event', attended_event_path(event), data: { 'turbo_method': :delete } %>
    <% end %>
</ul>